spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: meeting-reservation

springdoc:
  swagger-ui:
    path: /docs

payment:
  mock:
    base-url: ${MOCKPAY_BASE_URL:http://localhost:8081}
